data:
  train_batch_size: 64
  micro_batch_size: null # will be deprecated, use micro_batch_size_per_gpu
  micro_batch_size_per_gpu: 1  # this is also val batch size
  train_files: ~/data/coser_trainset/test_example/train.parquet
  val_files: ~/data/coser_trainset/test_example/test.parquet
  # Single-turn settings
  prompt_key: question
  response_key: answer
  prompt_dict_keys: ['question']
  response_dict_keys: ['answer']
  # Multi-turn settings
  multiturn:
    enable: false  # Set to true to use multi-turn dataset
    messages_key: messages  # Key for messages list in multi-turn mode
  max_length: 2048
  truncation: right
  balance_dp_token: False
  chat_template: null
  custom_cls:
    path: null
    name: null
model:
  partial_pretrain: /apdcephfs_cq10/share_1567347/share_info/llm_models/Qwen2.5-0.5B-Instruct
  fsdp_config:
    wrap_policy:
      min_num_params: 0
    cpu_offload: False
    offload_params: False
  external_lib: null
  enable_gradient_checkpointing: False
  trust_remote_code: False
  lora_rank: 0  # Set to positive value to enable LoRA (e.g., 32)
  lora_alpha: 16  # LoRA scaling factor
  target_modules: all-linear  # Target modules for LoRA adaptation
  use_liger: False
optim:
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.1
  clip_grad: 1.0
  lr_scheduler: cosine
ulysses_sequence_parallel_size: 1
use_remove_padding: False
trainer:
  default_local_dir: /apdcephfs_cq10/share_1567347/share_info/sorenliu/llm_model/cognitive_rl
  default_hdfs_dir: null # change the hdfs path here
  resume_path: null
  project_name: coser-sft-sample-1000
  experiment_name: test
  total_epochs: 2
  total_training_steps: null
  logger: ['console']
  seed: 1

